### ISSUE TITLE
Create a CI/CD pipeline to deploy to firebase

### ISSUE THREAD

**Issue by hkirat** [hkirat/leetcode-clone#30]
the backend

**Comment by hkirat** [comment]
Assume secrets can be put in github secrets

**Comment by initeshjain** [comment]
Source: https://github.com/marketplace/actions/deploy-to-firebase-cloud-functions

.github/workflows/firebase-deploy.yml

Add 2 secrets: FIREBASE_TOKEN and FIREBASE_PROJECT_ID

```
name: Deploy on Firebase
on:
  push:
    branches:
      - master
jobs:
  main:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jsryudev/deploy-firebase-functions@v0.0.2
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_ID }}
```
